# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# 这里写你的flutter module相对路径
flutter_application_path = '../flutter_module/'

target 'FluNative' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FluNative

  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')),binding)

end
